The pre-push hook reports unfetched remote commits
2021-04-05  Egeyar Bagcioglu  <egeyar@gmail.com>

        * etc/git-hooks/pre-push: Report it clearly when the pre-push hook
        fails due to remote containing unfetched commits.

diff --git a/etc/git-hooks/pre-push b/etc/git-hooks/pre-push
--- a/etc/git-hooks/pre-push
+++ b/etc/git-hooks/pre-push
@@ -42,8 +42,17 @@ do
 			# New branch, examine all commits
 			range="$local_sha"
 		else
-			# Update to existing branch, examine new commits
-			range="$remote_sha..$local_sha"
+			# Without this check, the "git diff-tree" below fails and
+			# this hook falsely reports "ChangeLog is missing." when the
+			# remote has unfetched commits.
+			if test $(git cat-file -t $remote_sha^{commit})
+			then
+				# Update to existing branch, examine new commits
+				range="$remote_sha..$local_sha"
+			else
+				echo "Remote contains unfetched commits"
+				exit 1
+			fi
 		fi
 
 		# Check for ChangeLog being in each commits
